import { dirname } from "node:path"
import { fileURLToPath } from "node:url"
import { FlatCompat } from "@eslint/eslintrc"

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) })

const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // `content/` is generated by `pnpm sync:docs`, `out/` by `next build`,
    // `public/api/` by the search-index step, and `next-env.d.ts` by Next.
    ignores: ["content/**", "out/**", ".next/**", "public/api/**", "next-env.d.ts"],
  },
  {
    rules: {
      // `const { titles: _titles, ...meta } = …` is how a field gets dropped
      // from an object; the binding is unused on purpose.
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", ignoreRestSiblings: true },
      ],
    },
  },
]

export default config
